package routes

import (
	"p2p_marketplace/backend/controller"
	"p2p_marketplace/backend/middleware"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/websocket/v2"
)

func AppRoutes(app *fiber.App) {
	publicLimiter := middleware.PublicRateLimiter()
	strictPublicLimiter := middleware.StrictPublicRateLimiter()
	privateLimiter := middleware.PrivateRateLimiter()

	// Public
	app.Post("/auth/signup", strictPublicLimiter, controller.SendEmailOTP)
	app.Post("/auth/login", strictPublicLimiter, controller.LogInUser)
	app.Post("/auth/verify-email", strictPublicLimiter, controller.SignUpUser)
	app.Post("/auth/resend-otp", strictPublicLimiter, controller.SendEmailOTP)
	app.Post("/auth/forgot-password", strictPublicLimiter, controller.ForgotPassword)
	app.Get("/listings", publicLimiter, controller.GetListings)
	app.Get("/listing/:id", publicLimiter, controller.GetListingById)
	app.Get("/locations/provinces", publicLimiter, controller.GetProvinces)
	app.Get("/locations/cities", publicLimiter, controller.GetCitiesMunicipalities)
	app.Get("/locations/barangays", publicLimiter, controller.GetBarangays)

	// Protected
	app.Get("/auth/me", controller.AuthenticateUser, privateLimiter, controller.Me)
	app.Delete("/auth/logout", publicLimiter, controller.Logout)
	app.Get("/auth/validate-reset-token", strictPublicLimiter, controller.ValidateResetToken)
	app.Post("/auth/reset-password", strictPublicLimiter, controller.ResetPassword)
	app.Post("/listing", controller.AuthenticateUser, privateLimiter, controller.CreateListing)
	app.Patch("/listing/:id/mark-complete", controller.AuthenticateUser, privateLimiter, controller.MarkListingAsComplete)
	app.Post("/listing/:id/report", controller.AuthenticateUser, privateLimiter, controller.ReportListing)
	app.Get("/listing/:id/review", controller.AuthenticateUser, privateLimiter, controller.GetMyListingReview)
	app.Post("/listing/:id/review", controller.AuthenticateUser, privateLimiter, controller.CreateListingReview)
	app.Put("/listing/:id/review", controller.AuthenticateUser, privateLimiter, controller.UpdateListingReview)
	app.Delete("/listing/:id/review", controller.AuthenticateUser, privateLimiter, controller.DeleteListingReview)
	app.Post("/listing/:id/bookmark", controller.AuthenticateUser, privateLimiter, controller.AddListingBookmark)
	app.Delete("/listing/:id/bookmark", controller.AuthenticateUser, privateLimiter, controller.RemoveListingBookmark)
	app.Get("/listing/:id/edit", controller.AuthenticateUser, privateLimiter, controller.GetListingEditById)
	app.Put("/listing/:id", controller.AuthenticateUser, privateLimiter, controller.UpdateListing)
	app.Patch("/listing/:id/toggle-visibility", controller.AuthenticateUser, privateLimiter, controller.ToggleListingVisibility)
	app.Delete("/listing/:id", controller.AuthenticateUser, privateLimiter, controller.DeleteListing)
	app.Get("/profile/me", controller.AuthenticateUser, privateLimiter, controller.MeProfile)
	app.Get("/profile/:id", controller.ProfileById)
	app.Put("/profile/me", controller.AuthenticateUser, privateLimiter, controller.UpdateMeProfile)
	app.Patch("/profile/me/images", controller.AuthenticateUser, privateLimiter, controller.UpdateMeProfileImages)
	app.Post("/profile/me/verification", controller.AuthenticateUser, privateLimiter, controller.SubmitMeVerification)
	app.Delete("/profile/me", controller.AuthenticateUser, privateLimiter, controller.DeactivateMeProfile)
	app.Get("/admin/dashboard/stats", controller.AuthenticateUser, privateLimiter, controller.GetAdminDashboardStats)
	app.Get("/admin/users", controller.AuthenticateUser, privateLimiter, controller.GetAdminUsers)
	app.Patch("/admin/users/:id/active", controller.AuthenticateUser, privateLimiter, controller.SetAdminUserActive)
	app.Delete("/admin/users/:id", controller.AuthenticateUser, privateLimiter, controller.DeleteAdminUser)
	app.Get("/admin/admins", controller.AuthenticateUser, privateLimiter, controller.GetAdminAccounts)
	app.Post("/admin/admins", controller.AuthenticateUser, privateLimiter, controller.CreateAdminAccount)
	app.Patch("/admin/admins/:id/active", controller.AuthenticateUser, privateLimiter, controller.SetAdminAccountActive)
	app.Delete("/admin/admins/:id", controller.AuthenticateUser, privateLimiter, controller.DeleteAdminAccount)
	app.Get("/admin/listings", controller.AuthenticateUser, privateLimiter, controller.GetAdminListings)
	app.Get("/admin/transactions", controller.AuthenticateUser, privateLimiter, controller.GetAdminTransactions)
	app.Patch("/admin/listings/:id/toggle-visibility", controller.AuthenticateUser, privateLimiter, controller.ToggleAdminListingVisibility)
	app.Delete("/admin/listings/:id", controller.AuthenticateUser, privateLimiter, controller.DeleteAdminListing)
	app.Get("/admin/reports", controller.AuthenticateUser, privateLimiter, controller.GetAdminReports)
	app.Patch("/admin/reports/:id/status", controller.AuthenticateUser, privateLimiter, controller.SetAdminReportStatus)
	app.Get("/admin/verifications", controller.AuthenticateUser, privateLimiter, controller.GetAdminVerifications)
	app.Patch("/admin/verifications/:id/status", controller.AuthenticateUser, privateLimiter, controller.SetAdminVerificationStatus)
	app.Get("/messages/conversations", controller.AuthenticateUser, privateLimiter, controller.GetConversations)
	app.Post("/messages/conversations/from-listing", controller.AuthenticateUser, privateLimiter, controller.CreateConversationFromListing)
	app.Get("/messages/conversations/:id", controller.AuthenticateUser, privateLimiter, controller.GetConversation)
	app.Patch("/messages/conversations/:id/offer", controller.AuthenticateUser, privateLimiter, controller.UpdateConversationOfferByOwner)
	app.Patch("/messages/conversations/:id/deal", controller.AuthenticateUser, privateLimiter, controller.ToggleConversationDealAgreement)
	app.Get("/messages/conversations/:id/messages", controller.AuthenticateUser, privateLimiter, controller.GetMessages)
	app.Post("/messages/conversations/:id/messages", controller.AuthenticateUser, privateLimiter, controller.SendMessage)
	app.Patch("/messages/conversations/:id/read", controller.AuthenticateUser, privateLimiter, controller.MarkMessagesRead)
	app.Patch("/messages/conversations/:id/messages/:messageId/reaction", controller.AuthenticateUser, privateLimiter, controller.ReactToMessage)
	app.Patch("/messages/conversations/:id/messages/:messageId", controller.AuthenticateUser, privateLimiter, controller.EditMessage)
	app.Delete("/messages/conversations/:id/messages/:messageId", controller.AuthenticateUser, privateLimiter, controller.DeleteMessage)
	app.Delete("/messages/conversations/:id", controller.AuthenticateUser, privateLimiter, controller.DeleteConversation)
	app.Get("/notifications", controller.AuthenticateUser, privateLimiter, controller.GetNotifications)
	app.Patch("/notifications/read-all", controller.AuthenticateUser, privateLimiter, controller.MarkAllNotificationsRead)
	app.Patch("/notifications/:id/read", controller.AuthenticateUser, privateLimiter, controller.MarkNotificationRead)
	app.Get("/ws", controller.AuthenticateUser, privateLimiter, controller.UpgradeRealtimeSocket, websocket.New(controller.RealtimeSocket))

	app.Post("/auth/otp/send", controller.AuthenticateUser, privateLimiter, controller.SendOTP)
	app.Post("/auth/otp/verify", controller.AuthenticateUser, privateLimiter, controller.VerifyOTP)
}
